Attempted tasks for Python - Network #0
